name = "angelito91"
main = "./dist/_worker.js/index.js"

compatibility_date = "2025-07-05"
compatibility_flags = ["nodejs_compat"]

workers_dev = false
preview_urls = false

[assets]
binding = "ASSETS"
directory = "./dist"
not_found_handling = "404-page"

[observability]
enabled = true
